### ISSUE TITLE
Setup new user permissions

### ISSUE THREAD

**Issue by vagos** [IEEE-SB-Univ-of-Patras/system-administration#5]
There should be a seperation between administratos and new users. 

New users should probably only have acess to their home directory and have acess to a subset of commands. 

If Linux works like that, we could have a group that has restricted permissions and then add new users to that group. 

* Figure out exactly what permissions new users should have.
* Setup an automated system that gives a user these permissions using a command like `add-new-user <name>`

**Comment by alkalyss** [comment]
I have setup the admin and basic groups, where the basic group has no sudo access and the admin group has full sudo access
